home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.index, name='index'),
]

miweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
urlpatterns = [
    path('admin/', admin.site.urls),
     path('', RedirectView.as_view(url='/home/', permanent=True)),
    path('home/', include('home.urls')),
    path('informacion/', include('informacion.urls')),
    path('principal/', include('principal.urls')),
    path("revista/", include("revista.urls")),
]

principal/urls.py
from django.urls import path
from . import views

app_name = "principal"
urlpatterns = [
    path('estudiantes/', views.estudiantes_view, name='estudiantes'),
    path('administradores/', views.administradores_view, name='administradores'),
    path("estudiantes/<int:pk>/detalle/", views.EstudianteDetailView.as_view(), name="estudiante_detalle"),
    path("estudiantes/<int:pk>/editar/", views.EstudianteUpdateView.as_view(), name="estudiante_editar"),
    path("administradores/<int:pk>/detalle/", views.AdministradorDetailView.as_view(), name="administrador_detalle"),
    path("administradores/<int:pk>/editar/", views.AdministradorUpdateView.as_view(), name="administrador_editar"),
]

principal/models.py
from django.db import models

# Create your models here.

principal/views.py
from django.views.generic import ListView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from revista.models import EstudiantePublicador, EstudianteAutorizador
from revista.forms import EstudiantePublicadorForm, EstudianteAutorizadorForm

def estudiantes_view(request):
    return render(request, 'principal/estudiantes.html')

def administradores_view(request):
    return render(request, 'principal/administradores.html')

def estudiantes_view(request):
    if request.method == "POST":
        form = EstudiantePublicadorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("principal:estudiantes")
    else:
        form = EstudiantePublicadorForm()

    estudiantes = EstudiantePublicador.objects.all()
    return render(request, "principal/estudiantes.html", {
        "form": form,
        "estudiantes": estudiantes
    })

def administradores_view(request):
    if request.method == "POST":
        form = EstudianteAutorizadorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("principal:administradores")
    else:
        form = EstudianteAutorizadorForm()

    administradores = EstudianteAutorizador.objects.all()
    return render(request, "principal/administradores.html", {
        "form": form,
        "administradores": administradores
    })

# Detalle
class EstudianteDetailView(DetailView):
    model = EstudiantePublicador
    template_name = "principal/estudiante_detalle.html"
    context_object_name = "estudiante"

class AdministradorDetailView(DetailView):
    model = EstudianteAutorizador
    template_name = "principal/administrador_detalle.html"
    context_object_name = "administradores"

# Edición
class EstudianteUpdateView(UpdateView):
    model = EstudiantePublicador
    fields = "__all__"
    template_name = "principal/estudiante_editar.html"
    success_url = reverse_lazy("principal:estudiantes")

class AdministradorUpdateView(UpdateView):
    model = EstudianteAutorizador
    fields = "__all__"
    template_name = "principal/administrador_editar.html"
    success_url = reverse_lazy("principal:administradores")

principal/templates/principal/administrador_detalle.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
<h2>Detalle del Estudiante</h2>
<p><strong>Nombre:</strong> {{ administradores.nombres}}</p>
<p><strong>Apellido:</strong> {{ administradores.apellidos}}</p>
<p><strong>Carnet:</strong> {{ administradores.carnet }}</p>
<p><strong>Correo:</strong> {{ administradores.correo }}</p>

<a href="{% url 'principal:administradores' %}" class="btn btn-secondary">Volver</a>
{% endblock %}

principal/templates/principal/administrador_editar.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
<h2>Editar Estudiante</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Guardar</button>
    <a href="{% url 'principal:administradores' %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock %}

principal/templates/principal/administradores.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
 <h2>Registrar Estudiante Autorizador</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Agregar </button>
 
</form>
 <button class="btn btn-info" onclick="toggleTabla()">Ver Listado</button>
<div id="tablaAdministradores" style="display:none; margin-top:20px;">
  <h3>Lista de Estudiantes Autorizadores</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Carnet</th>
        <th>Correo</th>
         <th>Opciones</th>
      </tr>
    </thead>
    <tbody>
      {% for admin in administradores %}
      <tr>
        <td>{{ admin.nombres }}</td>
        <td>{{ admin.apellidos }}</td>
        <td>{{ admin.carnet }}</td>
        <td>{{ admin.correo }}</td>
         <td>
          <a href="{% url 'principal:administrador_detalle' admin.pk %}" class="btn btn-info">Ver</a>
          <a href="{% url 'principal:administrador_editar' admin.pk %}" class="btn btn-warning">Editar</a>
        </td>
      </tr>
      {% empty %}
      <tr><td colspan="4">No hay administradores registrados</td></tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script>
function toggleTabla() {
    let tabla = document.getElementById("tablaAdministradores");
    if (tabla.style.display === "none") {
        tabla.style.display = "block";
    } else {
        tabla.style.display = "none";
    }
}
</script>
{% endblock %}

principal/templates/principal/estudiante_detalle.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
<h2>Detalle del Estudiante</h2>

<p><strong>Nombre:</strong> {{ estudiante.nombres}}</p>
<p><strong>Apellido:</strong> {{ estudiante.apellidos}}</p>
<p><strong>Carnet:</strong> {{ estudiante.carnet }}</p>
<p><strong>Correo:</strong> {{ estudiante.correo }}</p>

<a href="{% url 'principal:estudiantes' %}" class="btn btn-secondary">Volver</a>
{% endblock %}

principal/templates/principal/estudiante_editar.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
<h2>Editar Estudiante</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Guardar</button>
    <a href="{% url 'principal:estudiantes' %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock %}

principal/templates/principal/estudiantes.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
<h2>Registrar Estudiante Publicador</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Agregar</button>

</form>
<button class="btn btn-info " onclick="toggleTabla()">Ver Listado</button>
<div id="tablaEstudiantes" style="display:none; margin-top:20px;">
  <h3>Lista de Estudiantes Publicadores</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Carnet</th>
        <th>Correo</th>
        <th>Opciones</th>
      </tr>
    </thead>
    <tbody>
      {% for est in estudiantes %}
      <tr>
        <td>{{ est.nombres }}</td>
        <td>{{ est.apellidos }}</td>
        <td>{{ est.carnet }}</td>
        <td>{{ est.correo }}</td>
        <td>
          <a href="{% url 'principal:estudiante_detalle' est.pk %}" class="btn btn-info">Ver</a>
          <a href="{% url 'principal:estudiante_editar' est.pk %}" class="btn btn-warning">Editar</a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="4">No hay estudiantes registrados</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script>
  function toggleTabla() {
    let tabla = document.getElementById("tablaEstudiantes");
    if (tabla.style.display === "none") {
      tabla.style.display = "block";
    } else {
      tabla.style.display = "none";
    }
  }
</script>
{% endblock %}